# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: autentificare.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'autentificare.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61utentificare.proto\x12\x03idm\",\n\x0b\x43redentials\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06parola\x18\x02 \x01(\t\"\x19\n\x08Response\x12\r\n\x05token\x18\x01 \x01(\t2:\n\rAutentificare\x12)\n\x06\x43\x65rere\x12\x10.idm.Credentials\x1a\r.idm.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autentificare_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREDENTIALS']._serialized_start=28
  _globals['_CREDENTIALS']._serialized_end=72
  _globals['_RESPONSE']._serialized_start=74
  _globals['_RESPONSE']._serialized_end=99
  _globals['_AUTENTIFICARE']._serialized_start=101
  _globals['_AUTENTIFICARE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
